### ISSUE TITLE
test.cb swallows exceptions due to t.end() never being called.

### ISSUE THREAD

**Issue by rweng** [sindresorhus/ava#810] opened 2016-05-05 11:10 UTC
I've had some tests hanging due to a more complicated version of this test

```js
const fnWithUnexpectedException = (cb) => { throw 'this is not expected' };

test.cb('fnWithUnexpecttedException returns true', t => {
  fnWithUnexpectedException((res) => {
     t.is(res, 1)
     t.end()
   })
})
```

This keeps hanging because t.end is never reached. ava does not show the error and just runs in a timeout. So when writing tests, you basically have to wrap everything in a try catch block to ensure `t.end()` is being called:

```js
test.cb('fnWithUnexpecttedException returns true', t => {
    try {
      fnWithUnexpectedException((res) => {
        t.is(res, 1)
        t.end()
      })
    } catch(e) {
        t.fail(e)
        t.end()
    }
})
```

This seems to me to be a bit user unfriendly and, if new to ava as I am, can be a hard stumbling stone. I think the default behavior should be to fail the test on unexpected errors even in `test.cb`, because imho it is the more common use case and it is easier to debug in unexpected cases.

**Comment by novemberborn** [comment] 2016-05-06 16:21
Hi @rweng, this looks like a duplicate of #748. It should be fixed in master, could you try installing (`npm install sindresorhus/ava#master`) too see if that fixes it for you?

**Comment by jamestalmage** [comment] 2016-05-06 16:27
Also, you should always `throw new Error(message)`, instead of `throw message`.

**Comment by jamestalmage** [comment] 2016-05-06 16:37
Fixed in https://github.com/sindresorhus/ava/pull/774

**Closed by jamestalmage** 2016-05-06 16:37 UTC
