### ISSUE TITLE
TAP report prints test titles above not ok message

### ISSUE THREAD

**Issue by will-weiss** [sindresorhus/ava#679] opened 2016-03-23 15:01 UTC
## Description

The TAP report prints the failing assertion rather than the title of the test after the not ok message. If I have a test file `test.js` that reads:

```
import { test } from 'ava';

test('one should equal two', t => {
  t.is(1, 2);
});
```

and I run `ava --tap`, the resulting TAP report looks like this:

```
TAP version 13
# one should equal two
not ok 1 - 1 === 2
  ---
    operator: ===
    expected: 2
    actual: 1
    at: _callee$ (test.js:4:4)
  ...

1..1
# tests 1
# pass 0
# fail 1
```

This is an issue because I am using a [Jenkins TAP Plugin](https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin) that reports the titles of the tests incorrectly, as it interprets `1 - 1 === 2` as the name of the test. I would expect the TAP report to look like this:

```
TAP version 13
# one should equal two
not ok 1 - one should equal two
  ---
    operator: ===
    expected: 2
    actual: 1
    at: _callee$ (test.js:4:4)
  ...

1..1
# tests 1
# pass 0
# fail 1
```

If this is an issue with a dependency of ava and not with ava itself, please direct me to that project instead and I'll be happy to file an issue there.

Thanks in advance!

## Environment
Node.js v5.9.0
darwin 14.5.0

**Comment by novemberborn** [comment] 2016-04-05 17:13
Hi @will-weiss thanks for your report. I believe this is a duplicate of #324.

**Comment by novemberborn** [comment] 2016-04-05 17:31
Actually I'm not sure now. @jamestalmage?

**Comment by jamestalmage** [comment] 2016-04-05 17:46
Yeah - This is a legit issue. Related to #324, but not identical. I have `tap-emitter` in the works. [help-wanted](https://github.com/jamestalmage/tap-emitter/issues)

**Comment by sotojuan** [comment] 2016-04-06 17:55
@jamestalmage For now is it fine to submit a PR that changes

`format('not ok %d - %s', ++this.i, test.error.message),`

with

`format('not ok %d - %s', ++this.i, test.title),`

In `lib/reporters/tap.js`? Seems like that would emit the output @will-weiss wants.

**Comment by jamestalmage** [comment] 2016-04-06 18:00
Works for me.

**Closed** 2016-04-09 04:50 UTC
Labels: bug, help wanted
