### ISSUE TITLE
Stop on first failed assertion

### ISSUE THREAD

**Issue by jankuca** [sindresorhus/ava#220] opened 2015-11-16 10:11 UTC
I noticed that test cases are not stopped when an assertion fails. To be exact, they are stopped asynchronously. Here is an example:

```
test(t => {
  let arr = [ { name: 'abc' } ];
  t.is(arr.length, 2);
  t.is(arr[1].name, 'xyz');
  t.end();
});
```

The error I'd expect to see is "1 !== 2" while the actual error I get is "cannot read property 'name' of undefined" because execution is not stopped on the failed assertion (on the line above).

Is there a reason why `Test#exit()` is called asynchronously (by `Test#_assert()`) rather than synchronously (which is the case for errors thrown outside assertions)?

**Comment by jamestalmage** [comment] 2015-11-23 00:19
Duplicate of #121 

Fix PR: #259

**Closed** 2015-11-23 03:29 UTC
