### ISSUE TITLE
How to use with iron-node?

### ISSUE THREAD

**Issue by jantimon** [sindresorhus/ava#803] opened 2016-05-02 11:33 UTC
Is there any support for using ava together with tools like iron-node or would jasmine/mocha/tap be a better fit then?

**Comment by jamestalmage** [comment] 2016-05-04 20:45
There is, but it's broken ATM. See #798.

If you go back a version or two it might work.

You can find information on how to use it in `contributing.md` or `maintaining.md`.

**Comment by jantimon** [comment] 2016-05-05 23:08
So better go with jasmine and mocha or tap?
Ava says it's futuristic but debugging with console.log is ancient ;)

**Comment by jamestalmage** [comment] 2016-05-06 02:31
Closing as a duplicate of #798.

Fix is in #812

**Closed by jamestalmage** 2016-05-06 02:31 UTC

**Comment by jantimon** [comment] 2016-05-06 10:06
How are those two issues related?
Is there anything I can do to support this?
What is the state of #812?

**Comment by jamestalmage** [comment] 2016-05-06 12:46
> How are those two issues related?

Read this: https://github.com/sindresorhus/ava/blob/master/maintaining.md#profiling

> What is the state of #812?

You can track progress by subscribing to that PR. Currently only tests on Windows are failing.

> Is there anything I can do to support this?

1. Figure out why Windows tests are failing in #812
2. Write a Recipe on using the profile script. The section in `maintaining.md` is a good start, but add some introductory information on `iron-node`, and add some screenshots, etc. Probably best to change the focus from profiling to debugging.

**Comment by jantimon** [comment] 2016-05-06 13:21
Okay thanks very much - I am on the road right now - so I can't promise to much but if I can find some time I'll try to figure out why your two profile tests fail on windows.
