### ISSUE TITLE
TAP output not sending the correct number of asserts

### ISSUE THREAD

**Issue by JaKXz** [sindresorhus/ava#401] opened 2016-01-02 20:32 UTC
From zoubin/tap-summary#2 

Reproducible with: https://gist.github.com/JaKXz/c676f6b5493b0ce90225
- just download the zip and run `npm install && npm test` [assuming you have `tee` on your system, if not just drop the last pipe]

There should be 4 asserts and 2 tests in the output there, but the tests and asserts are printed as the same.

Ideally, the assertion output would include the message from the corresponding assertion.

I also tried `t.plan(2)` in the second test only (#25) and that didn't make any difference.

**Comment by jamestalmage** [comment] 2016-01-02 22:28
AVAs tap output doesn't currently show individual assertions, just outputs tests.

Closing as a duplicate of #324.

**Closed by jamestalmage** 2016-01-02 22:28 UTC
