### ISSUE TITLE
"Maximum call stack size exceeded" from espurify

### ISSUE THREAD

**Issue by MoOx** [sindresorhus/ava#274] opened 2015-11-26 15:45 UTC
This test is ok

```js
import "babel-core/register"
import test from "ava"

import React from "react"
import ReactDOMServer from "react-dom/server"

test("failure", (t) => {
  const inlinedSvg = ReactDOMServer.renderToStaticMarkup(
    <div />
  )
  t.is(
    inlinedSvg,
    `<span class="SVGIcon TestSVG"><svg class="SVGIcon-svg TestSVG-svg"` +
    `><g></g></svg></span>`,
    "passes & merges className"
  )

  t.end()
})
```

But this one create an issue

```js
import "babel-core/register"
import test from "ava"

import React from "react"
import ReactDOMServer from "react-dom/server"

test("failure", (t) => {
  
  t.is(
    ReactDOMServer.renderToStaticMarkup(
      <div />
    ),
    `<span class="SVGIcon TestSVG"><svg class="SVGIcon-svg TestSVG-svg"` +
    `><g></g></svg></span>`,
    "passes & merges className"
  )

  t.end()
})
```

Error

```
❯❯ ava "src/__tests__/*.js"

Uncaught Exception:  /Users/MoOx/Sync/Development/react-svg-inline/src/__tests__/index.js
  RangeError: /Users/MoOx/Sync/Development/react-svg-inline/src/__tests__/index.js: Maximum call stack size exceeded
    at cloneProperty (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/espurify/lib/clone-ast.js:46:17)
    at cloneObj (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/espurify/lib/clone-ast.js:40:13)
    at cloneContainer (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/espurify/lib/clone-ast.js:17:20)
    at cloneOf (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/espurify/lib/clone-ast.js:56:24)
    at cloneProperty (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/espurify/lib/clone-ast.js:47:30)
    at cloneObj (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/espurify/lib/clone-ast.js:40:13)
    at cloneContainer (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/espurify/lib/clone-ast.js:17:20)
    at cloneOf (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/espurify/lib/clone-ast.js:56:24)
    at cloneProperty (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/espurify/lib/clone-ast.js:47:30)

Error: Test results were not received from: /Users/MoOx/Sync/Development/react-svg-inline/src/__tests__/index.js
    at ChildProcess.<anonymous> (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/ava/lib/fork.js:51:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
From previous event:
    at module.exports (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/ava/lib/fork.js:23:16)
    at run (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/ava/cli.js:112:9)
    at Array.map (native)
    at /Users/MoOx/Sync/Development/react-svg-inline/node_modules/ava/cli.js:195:22
From previous event:
    at init (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/ava/cli.js:187:4)
    at Object.<anonymous> (/Users/MoOx/Sync/Development/react-svg-inline/node_modules/ava/cli.js:234:2)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

Some infos:

❯ node --version
v5.0.0

❯ npm --version
3.5.1

babel 5.8.x

**Comment by twada** [comment] 2015-11-26 16:44
@MoOx Thank you for reporting and reproduction case.

Currently, power-assert only supports standard AST Nodes defined in [The ESTree Spec](https://github.com/estree/estree).
JSX nodes are not supported.

I'll fix this when AVA gets Babel 6 ready.
I'm so sorry for the inconvenience.

**Comment by MoOx** [comment] 2015-11-27 09:38
So why the first example is working? (Reminder I use babel 5.8 for the moment since lots of things are not working/ready for 6)

**Comment by twada** [comment] 2015-11-27 10:14
@MoOx 

> So why the first example is working?

In the first example, JSX element is on the __outside__ of assertion argument expression (in this case, arguments of `t.is`) so power-assert ignored it.

In the second example, JSX element is on the __inside__ of assertion argument expression, so power-assert tried to infer more information, and something wrong has occurred.

**Comment by jamestalmage** [comment] 2015-12-01 03:06
Closing since this is not an AVA issue, but a power-assert one.

I opened https://github.com/power-assert-js/power-assert/issues/34 to track this issue there.

**Closed** 2015-12-01 03:06 UTC

**Comment by twada** [comment] 2016-03-09 15:51
Now I'm working with it.

refs: [[WIP][experimental] Big refactoring: Embed assertion's AST and tokens to make runtime side parser unnecessary](https://github.com/power-assert-js/babel-plugin-espower/pull/13)
