### ISSUE TITLE
Readme question - installing globally

### ISSUE THREAD

**Issue by davidhq** [sindresorhus/ava#581] opened 2016-03-01 12:11 UTC
Readme suggests installing ava globally but then 

`import test from 'ava';`

line in all tests fails, because you cannot require global modules.

I really want to have ava only once, it has 300 dependencies and it takes a long time to install in each project. 

Is there a way to have to only once and still run tests?

**Comment by vdemedes** [comment] 2016-03-01 12:28
I'm afraid it's a bad practice to use global modules in your projects. Each project has to be complete, with its own dependencies. Plus, when you'll want to test it on CI, you will have to install AVA locally anyway. So I wouldn't recommend going that path.

**Comment by davidhq** [comment] 2016-03-01 12:31
I thought so... but still then update readme to be more clear for beginners?

And I guess it's neccessary for ava to have 300 deps but still I think for me it is unacceptable to have it in each project ... I already gave one project to a friend and he commented that it's installing a lot of deps, I agree. 

Still a great project...

**Comment by vdemedes** [comment] 2016-03-01 12:35
Yes, we are aware about the slow installation of AVA, but we actually need all those dependencies to provide a great experience, which users expect from AVA.

We will definitely try to minimize dependencies, but given that our biggest dependency is babel, I'm not sure we can do much in that area.

Glad you like AVA and let us know if any other suggestions come up ;)

**Comment by novemberborn** [comment] 2016-03-01 14:33
The README says to install globally *and then* run `ava --init`. I'd rather it said `npm install --save-dev ava` and suggested using `ava` for the `test` script. Not convinced about the `init` command TBH.

**Comment by davidhq** [comment] 2016-03-01 14:34
Related to this: `ava --init` command "hangs" on my machine.. I mean it updates `package.json` but I waited and waited, then realized it's not doing anything and exited with ctrl+c. 

I'm on latest OSX

**Comment by vdemedes** [comment] 2016-03-01 15:21
`ava --init` works, but very long, because `npm install` takes a long time.

**Comment by vdemedes** [comment] 2016-03-01 15:21
I assume we can close this now.

**Closed by vdemedes** 2016-03-01 15:21 UTC
Labels: question

**Comment by novemberborn** [comment] 2016-03-01 15:23
> ava --init works, but very long, because npm install takes a long time.

That's silly though. The user just waited a long time to globally install AVA and then they have to wait again for the local install. Why bother with the `ava --init` route at all?

**Comment by sindresorhus** [comment] 2016-03-01 15:59
@novemberborn We recommend users install it globally so they can use the local AVA directly by typing AVA. Local because that's how Node.js works. Why `--init`? Well, it's a nice way to get started. They would have to npm install anyways, and `init` adds to package.json run script too. npm should cache dependencies, so installing it locally after doing it globally should be faster than the first time. The slow npm speed really pains me as users always blame the project, not npm, while it's almost totally out of our control. Alternative npm clients have shown it's possible to speed it up considerably without any server changes. Anyhow. What we can do is to show the npm progress bar in `--init` during install: https://github.com/sindresorhus/ava-init/issues/2

**Comment by sindresorhus** [comment] 2016-03-01 16:00
> I really want to have ava only once, it has 300 dependencies and it takes a long time to install in each project.

Use a better npm client. https://github.com/alexanderGugel/ied is known to be faster.

**Comment by sindresorhus** [comment] 2016-03-01 16:02
> And I guess it's neccessary for ava to have 300 deps but still I think for me it is unacceptable to have it in each project ...

You should read up on why it's like this with Node.js. Nothing specifically to do with this project. Having local unique dependencies in each project gives you a lot of benefits too. If all dependencies are global, every project would potentially conflict dependency-wise.

**Comment by novemberborn** [comment] 2016-03-01 18:27
> We recommend users install it globally so they can use the local AVA directly by typing AVA.

Fair enough. I've gotten into the habit of using `$(npm bin)/ava` and I frequently update my local Node install in such a way that global packages don't carry over, so I rarely install anything globally.

**Comment by sindresorhus** [comment] 2016-03-01 18:29
@novemberborn Yup, that's a better workflow. Unfortunately most don't do that.

**Comment by davidhq** [comment] 2016-03-03 01:19
@novemberborn how exactly do you use that `$(npm bin)/ava` ?  I don't understand.

@sindresorhus thank you for ied! I will definitely see.... 

I understand that slowness is not your problem. but still something is wrong with the default thing, I have to learn more.

**Comment by novemberborn** [comment] 2016-03-03 11:04
Hi @davidhq, I use OS X with zsh so this may not apply to your situation. `npm bin` returns the `node_modules/.bin` folder relative to the closest `package.json`. In the Terminal `$(npm bin)/ava` expands to `/path/to/node_modules/.bin/ava` which runs the AVA installed in my current project.

**Comment by spadin** [comment] 2016-04-28 22:32
Does running `$(npm bin)/ava` still work? When I `ls $(npm bin)` I don't see `ava` in there. I'd like a way to use `ava` without the global install. Is that possible?

**Comment by jfmengels** [comment] 2016-04-28 22:36
@spadin If you have a `package.json`, you could make AVA a script:
```json
  "scripts": {
    // either or both of them
    "test": "eslint . && ava",
    "ava": "ava"
  },
```
then run `npm run ava` or `npm run test` to run AVA without having it globally.

**Comment by spadin** [comment] 2016-04-28 22:45
Maybe I should open an issue. But having a similar `scripts` section in my `package.json` I get the following error. 

```sh
$ npm run test

> frontendapp@0.0.1 test /Users/sandropadin/code/spadin/frontendapp
> ava

sh: ava: command not found
```

But it works when I have `ava` installed globally.

Here's a link to my [package.json][https://github.com/spadin/frontendapp/blob/master/package.json], also I'm using Node v6.0.0 if that makes a difference.

**Comment by spadin** [comment] 2016-04-28 23:31
Hmm. Sorry, please ignore my previous comment. I `rm -rf node_modules` and `npm install`ed again and it worked. Couldn't reproduce the error message above.
