### ISSUE TITLE
Code coverage ES6

### ISSUE THREAD

**Issue by FuzzOli87** [sindresorhus/ava#185] opened 2015-11-10 23:11 UTC
Hello,

You guys recommend to use NYC for coverage since it can handle spawned files. However, when testing since I have to transpile it first, it uses the transpiled code to test for coverage.

Is there a way to configure it so that it does not do this and so that it uses the ES6 code?

**Comment by jamestalmage** [comment] 2015-11-11 00:05
NYC relies on `istanbul`. See this issue: https://github.com/gotwarlost/istanbul/issues/212

`istanbul` has a `source-map` branch that looks like it is getting pretty close, but looks like [it doesn't play well with some reporters](https://github.com/gotwarlost/istanbul/issues/212#issuecomment-154707794).

I have [been told](https://github.com/jamestalmage/istanbul-combine/issues/2#issuecomment-155173813) that integrating `istanbul-combine` solves the issue, but I never got around to it.

If you can't wait for istanbul and NYC to release source map support, I recommend trying to fork NYC to use the istanbul source-map branch. If you run into issues combining coverage files checkout `istanbul-combine`

**Comment by FuzzOli87** [comment] 2015-11-12 19:00
@jamestalmage 

Interesting. I should of done a bit more research before asking but I was stuck in traffic and I had it in my head. I'll give it a spin and report back.

**Comment by novemberborn** [comment] 2015-11-16 17:10
There's also <https://github.com/SitePen/remap-istanbul>. This seems to work for me:

```
nyc --reporter=json npm test
mv coverage/coverage-final.json coverage/coverage.json
remap-istanbul -i coverage/coverage.json -o coverage/coverage.json
istanbul report lcov
```

**Comment by jamestalmage** [comment] 2015-11-25 04:35
@novemberborn With https://github.com/sindresorhus/ava/commit/fb98d5dcff7ac4810efa5ef5ee42b0d041c89d13 merged where do we stand on this?

Can this be closed, or is this a different issue?

**Comment by novemberborn** [comment] 2015-11-25 11:36
@jamestalmage it's a different issue. Code coverage is computed over the compiled output, so the stats will be wrong and it's hard to see which line in the original code was not covered. `remap-istanbul` uses source maps to compute the coverage of the original source.

The approach I mentioned above works for my project, which uses a watcher to transpile source files and write them to disk, with their source maps. *That output* is what's tested. It not quite a one-line though and it depends heavily on your project is set up.

This isn't an issue with AVA though.

**Comment by novemberborn** [comment] 2015-11-25 11:37
> This isn't an issue with AVA though.

By which I mean, since AVA isn't responsible for the coverage reports, it's not a bug with the project. Workarounds could be explained (maybe I should do so! :wink:) but it's fairly tricky.

**Comment by novemberborn** [comment] 2015-11-26 12:42
Here's the writeup of my workaround: https://medium.com/@novemberborn/code-coverage-with-babel-istanbul-nyc-83b8c2f1093

**Comment by mindmelting** [comment] 2015-11-30 01:53
I think the latest release of nyc now works out the box... (or at least it does for me!)

**Comment by jamestalmage** [comment] 2015-11-30 02:45
@bcoe,
I want to make sure AVA is able to take advantage of the latest `nyc` source-map goodness. We are doing a couple things that I suspect *may* interfere. I'm just going to list them; If you can tell me if anything sounds problematic, I'd appreciate it.

1. AVA transpiles test files only, and avoids `babel-core/register` by default. This allows users to write tests in ES2015, even when they prefer to keep their module code in ES5 (good for small modules where you don't want a build step). If users want transpile their main modules, they need to call the register hook themselves.

2. We want to allow "helper" files in the test folder (utilities that are shareable between tests). Currently that just means, any file with a `_` prefix. We will be hooking `require` to automatically transpile these as well (all other files will pass through unmodified by default). I see https://github.com/bcoe/nyc/pull/58 hooks `require` as well. I also saw your discussion here: https://github.com/babel/babel/pull/3062. Any pointers as I implement AVA's require hook so I don't clobber `nyc` source-map support?

3. We also intend to implement transpilation caching. If a file has not changed since last run, we will reuse the old transpilation result. We will store cached results as files  in a temp folder, named according to the hash of their contents (with periodic deletion of least recently used items). This means the transpiled source (and attached sourcemap) will likely not be where `nyc` expects to find it. Assuming `nyc` instruments coverage on top of transpiled files, and then uses source-maps after the fact to generate coverage for the original source after the fact, we would probably need a way to tell `nyc` where to find source-map information for a given file.

I look forward to your response. Thanks for your time, and for making `nyc` awesome!

**Comment by bcoe** [comment] 2015-11-30 04:44
1. nyc executes first, so the logic that sets aside Babel's require hook using getters/setters should also work for AVA:

https://github.com/bcoe/nyc/blob/master/index.js#L138

2. here's the flow that nyc uses for Babel, I think we could probably use a similar approach:

* nyc delegates to AVA's require hook which will return the transpiled code with a source-map appended.
* nyc will, in turn, instrument this transpiled code with test coverage.
* using the source maps, nyc will report coverage that references the original pre-transpiled code.

3. If we implement things like we've outlined in 2., I think that only AVA's require hook will need to know about the cache.
  nyc will be collecting coverage that references the pre-transpiled files.

Let me know anything I can do to help you implement this, feel free to point me at any branches that are
works in progress.

**Comment by jamestalmage** [comment] 2015-11-30 04:52
Thanks for the quick response. We will follow up as we move those initiatives along.

**Comment by novemberborn** [comment] 2015-12-01 20:56
> We might find that the nyc -> AVA -> babel-core/register interaction is an issue (perhaps nyc will need to store a stack of require hooks).

https://github.com/bcoe/nyc/pull/65 takes care of that.

> nyc delegates to AVA's require hook which will return the transpiled code with a source-map appended.

This might have to be documented better on nyc's side, I'll look into that.

That said, the test files don't need to be instrumented, the source files that are being tested do. It would help though if AVA's documentation could explain the requirements so users don't have to read up on nyc. I'll look into that when things settle with nyc.

**Comment by sparty02** [comment] 2015-12-04 15:10
I tried ```nyc``` with ```ava``` and failed...  :cry:   I feel like I'm doing something really simple wrong.  

Here's a snippet of my run scripts:

```js
"scripts": {
    "test": "ava src/test/**/*.js",
    "coverage": "nyc npm test"
}
```

Any chance someone on this thread could assist in some light guidance?  I'd be happy to follow up with some ```README``` updates.

**Comment by jamestalmage** [comment] 2015-12-04 15:12
```diff
"scripts": {
-    "test": "ava src/test/**/*.js",
+    "test": "nyc ava src/test/**/*.js",
    "coverage": "nyc npm test"
}
```

**Comment by sparty02** [comment] 2015-12-04 15:14
@jamestalmage with that change, running ```npm test```   :

```
> nyc ava src/test/**/*.js

module.js:339
    throw err;
    ^

Error: Cannot find module '[ path to my package root ]\ava'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
```

**Comment by jamestalmage** [comment] 2015-12-04 15:15
have you installed ava locally?

`npm install --save-dev ava`

**Comment by sparty02** [comment] 2015-12-04 15:16
Yeah, ava runs just fine by itself.  Here is a snippet from my dev deps:
```
"devDependencies": {
    "ava": "^0.7.0",
    "nyc": "^4.0.1"
}
```

**Comment by jamestalmage** [comment] 2015-12-04 15:21
Huh, 
Delete your `node_modules` folder then:
```
npm cache clean && npm install
```

**Comment by sparty02** [comment] 2015-12-04 15:31
Tried that, no dice.... same error as above....  :disappointed:

**Comment by novemberborn** [comment] 2015-12-05 17:28
@sparty02 what Node and npm versions are you running?

**Comment by sparty02** [comment] 2015-12-07 14:48
node v4.2.0
npm v3.5.2

**Comment by novemberborn** [comment] 2015-12-07 17:45
@sparty02 wait you're on Windows right? nyc's Windows support isn't quite there yet, we'll be tracking progress in <https://github.com/bcoe/nyc/issues/81>.

**Comment by sparty02** [comment] 2015-12-07 18:01
@novemberborn Ah, that must be it then.  I'll watch that issue for updates.... thanks!

**Comment by bcoe** [comment] 2015-12-10 16:19
@sparty02 we've added better support for Windows subprocesses in `yargs@5.0.0`:

https://github.com/bcoe/nyc/blob/master/CHANGELOG.md

It might be worth giving this a shot. If you still run into problems, could you point me at a repo I can test against?

**Comment by sindresorhus** [comment] 2015-12-21 02:41
> It might be worth giving this a shot. If you still run into problems, could you point me at a repo I can test against?

@sparty02 Did that solve your problem? If no, would you be able to provide something that reproduces it?

**Comment by sparty02** [comment] 2015-12-21 04:49
@bcoe @sindresorhus sorry guys, I spaced out on this.  I'll give it a shot tomorrow morning and circle back to let you know.

**Comment by sparty02** [comment] 2015-12-21 14:46
@bcoe I pushed a sample repo at https://github.com/sparty02/nyc-ava-demo.  I stripped it down to almost nothing, and am still hitting the issue, so it almost seems environmental?  Let me know if I can provide any more info!

**Comment by sparty02** [comment] 2016-01-03 17:33
@bcoe @sindresorhus Just a heads up that I saw some activity over on nyc that was done in the past few days that appeared to (at least loosely) be related to better spawn support on Windows.  Long story short, I just tried my use case again with ```ava@0.9.1``` and ```nyc@5.2.0``` and it worked!

**Closed** 2016-02-29 14:24 UTC
Labels: question

**Comment by AutoSponge** [comment] 2016-05-27 18:43
@sparty02 I just set this up on a windows machine and it works but I couldn't use `nyc npm test` in my scripts. `nyc ava` works just fine.
