### ISSUE TITLE
babel.Transformer TypeError: undefined is not a function

### ISSUE THREAD

**Issue by tanraya** [sindresorhus/ava#329] opened 2015-12-13 05:14 UTC
Hi!

I have following test (es6):

```es6
import test from 'ava';

test('does something', t => {
  t.same(true, true);
});
```

and following deps:

```
  "devDependencies": {
    "babel-cli": "^6.3.17",
    "babel-core": "^6.3.17",
    "babel-preset-es2015": "^6.3.13",
    "ava": "^0.7.0"
  },
  "dependencies": {
    "postcss": "^5.0.12"
  }
```

When I'm run `ava` command I'm getting this error:

```
    return new babel.Transformer('babel-plugin-espower', createEspowerVisitor(babel, options));
           ^
TypeError: undefined is not a function
    at createEspowerPlugin (/home/tanraya/sandbox/open-source/postcss-easywyg-describe/node_modules/ava/node_modules/babel-plugin-espower/create.js:6:12)
```

Can anyone help me to fight this error? I'm honestly confused  with that kind of error.

**Comment by jamestalmage** [comment] 2015-12-13 05:36
Bad news:  You can't use Babel 6 yet.
Good news: The fix is in master (https://github.com/sindresorhus/ava/commit/d0c370a1c00db8c02e9d7c4bcbac835b1a6c8a08)

Are you using Babel for your production code, or just in your tests?

If just in tests, then do not install Babel as a dependency at all (it will end up being a duplicate of what AVA installs). AVA will handle handle setting up babel automatically for your tests.
 
If you need to transform your own production code using Babel, then you are stuck using Babel 5 ATM (unless you want to be bold and work from master).

Closing as a duplicate of #207

**Closed by jamestalmage** 2015-12-13 05:36 UTC

**Comment by tanraya** [comment] 2015-12-13 06:53
@jamestalmage Thank you. Now it's clear.
