### ISSUE TITLE
Recipe for switching from Tape to AVA

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#445] opened 2016-01-17 15:00 UTC
@jamestalmage commented some things on Gitter:

> - The assertion API’s are similar, but not exact. Especially when it comes to truthy vs strictly true, and == vs ===.
> - Most of the gotchas for newcomers surround AVA’s async behavior. Specifically, don’t store mutable data in a closure scope (i.e. accessible from multip tests). Use t.context instead.
> - It goes without saying that you should read the readme thoroughly. But also read through the release notes.

I'd add:

- `t.plan()` doesn't implicitly end the test.
- `test.cb()` for callback tests.

What else?

**Comment by MoOx** [comment] 2016-01-17 21:35
My 2 cents:

- t.equal => t.is
- t.deepEqual => t.same
- no need for t.end() in most case

**Comment by jamestalmage** [comment] 2016-01-17 22:10
I think it would be really helpful if, along with the recipe, there was a "conversion cheat sheet" (maybe in a table or something). That listed all the commands:

`node-tap` | `tape` | `ava` | notes
---------------|---------|---------|---------
`t.equal` | `t.equal`| `t.is`|
`t.throws` | `t.throws` | `t.throws`| `ava` also accepts a `Promise` in addition to functions.
... |
... |

I'm not sure if it's necessary to have separate `node-tap` / `tape` columns or not.

**Comment by novemberborn** [comment] 2016-04-05 15:12
Closing as a duplicate of #445.

**Closed by novemberborn** 2016-04-05 15:12 UTC
Labels: docs, good for beginner, help wanted

**Comment by sindresorhus** [comment] 2016-04-05 15:22
@novemberborn This is #445 😝

**Comment by novemberborn** [comment] 2016-04-05 15:28
Ha, meant #178 :wink:
