### ISSUE TITLE
tests always pass bug

### ISSUE THREAD

**Issue by willin** [sindresorhus/ava#765] opened 2016-04-16 04:10 UTC
## Description

```js
test('View 200', (t) => {
  server.inject({
    method: 'GET',
    url: '/login'
  }, (response) => {
    console.log(response.statusCode); // 200
    t.deepEqual(response.statusCode, 789); // not equal
  });
});
```

```
ava -v

  ✔ login › View 200
  ✔ index › Redirect 302
  ✔ login › Success 200
  ✔ doc › Redirect 302
200
> |
```

## Environment

v0.14.0

Node.js v5.10.1
darwin 15.4.0
hapi 13.2.1

**Comment by willin** [comment] 2016-04-16 04:29
### ERROR

```js
test('View 200', async(t) => {
  const response = await server.inject({
    method: 'GET',
    url: '/login'
  });
  console.log(response.statusCode); // 200
  t.deepEqual(response.statusCode, 789); // not equal, fail
});
```

```
ava -v

  ✔ index › Redirect 302
  ✔ doc › Redirect 302
200
(node) Server.connections property is deprecated. Use Server.getConnections method instead.
```

### SUCCESS

```js
test('View 200', async(t) => {
  const response = await server.inject({
    method: 'GET',
    url: '/login'
  });
  console.log(response.statusCode); // 200
  t.deepEqual(response.statusCode, 200); // equal, success
});
```

```
ava -v

  ✔ index › Redirect 302
  ✔ doc › Redirect 302
200
  ✔ login › View 200

  3 tests passed
> |
```

**Comment by jamestalmage** [comment] 2016-04-16 04:43
@willin 
Not sure I understand the problem, but here's my thoughts on your three examples:

Your first example will hang forever. It needs to use `t.cb`:

```js
test.cb('View 200', (t) => {
  server.inject({
    method: 'GET',
    url: '/login'
  }, (response) => {
    console.log(response.statusCode); // 200
    t.deepEqual(response.statusCode, 789); // not equal
    t.end(); // you need to call t.end() when using `test.cb`
  });
});
```

Your second example should fail since `200 !== 789`.
Your third example looks like it should pass, which it apparently does.

Can you provide a more detailed description of what's going wrong?

**Comment by sindresorhus** [comment] 2016-04-16 05:12
> Your first example will hang forever.

@jamestalmage It won't. Sync tests end in the same tick. But yeah, needs to use `test.cb()`. Any way we could catch this mistake in `eslint-plugin-ava`? I think we'll see more of this as people move from tap/tape.

**Comment by willin** [comment] 2016-04-16 05:30
```js
test('View 200', (t) => {
  server.inject({
    method: 'GET',
    url: '/login'
  }, (response) => {
    console.log(response.statusCode); // 200
    t.deepEqual(response.statusCode, 789); // not equal
  });
});
```

```
ava -v

  ✔ login › View 200
  ✔ index › Redirect 302
  ✔ login › Success 200
  ✔ doc › Redirect 302
200
> |
```

should fail


and tried:

```js
test.cb('View 200', (t) => {
  server.inject({
    method: 'GET',
    url: '/login'
  }, (response) => {
    console.log(response.statusCode); // 200
    t.deepEqual(response.statusCode, 789); // not equal
    t.end(); // you need to call t.end() when using `test.cb`
  });
});
```

```
ava -v

  ✔ index › Redirect 302
  ✔ doc › Redirect 302
  ✔ login › View 200
200
(node) Server.connections property is deprecated. Use Server.getConnections method instead.
```

**Comment by sindresorhus** [comment] 2016-04-16 05:32
> should fail

No it shouldn't. In that case you're incorrectly using an async callback in a sync test. The test ends before the callback is executed.

> and tried:

What's the problem here?

**Comment by jamestalmage** [comment] 2016-04-16 05:48
> What's the problem here?

I think it's that:

```js
    console.log(response.statusCode); // 200
    t.deepEqual(response.statusCode, 789); // not equal
```

Produces output:

```
  ✔ login › View 200
200
```

Which makes no sense. The log statement prints after the tests passes (and the test passes).

I've tried to reproduce, thinking there's maybe some problem with `deepEqual` when used to compare literals (there does not appear to be).

@willin - Something doesn't seem right. Can you post some code to a GitHub repo that we can use to reproduce?

**Comment by willin** [comment] 2016-04-16 06:18
server.inject doc: <http://hapijs.com/api#serverinjectoptions-callback>

sample server: <http://hapijs.com/tutorials>

**Comment by jamestalmage** [comment] 2016-04-16 06:24
@willin. 

Please post some of your own code on GH in a repo we can clone that shows the problem.

**Comment by jamestalmage** [comment] 2016-05-07 07:28
Closing as OP is non-responsive.

@willin - If you are able to elaborate on the problem more, and provide a minimal reproduction, please open a new issue.

**Closed by jamestalmage** 2016-05-07 07:28 UTC
Labels: question

**Comment by midnightcodr** [comment] 2016-07-26 18:22
Although this issue has been closed. I found something interested. The following code outputs the node warning (_Server.connections property is deprecated. Use Server.getConnections method instead_.) and process hangs
```javascript
test.cb('hello', (t)=> {
	server.inject('/hello', (res) => {
		t.is(res.statusCode, 300);
		t.end();
	});
});
```

But the following code results in expected result (test fails and process doesn't hang):
```javascript
test.cb('hello', (t)=> {
	server.inject('/hello', (res) => {
		const code=res.statusCode
		t.is(code, 300);
		t.end();
	});
});
```

**Comment by novemberborn** [comment] 2016-09-21 09:53
@midnightcodr I'd guess in the former example `power-assert` is getting stuck serializing `res`. If this is still an issue with the latest version would you mind opening a new issue?
