### ISSUE TITLE
`NODE_PATH` does not work

### ISSUE THREAD

**Issue by inyono** [sindresorhus/ava#515] opened 2016-02-06 01:37 UTC
We are using `NODE_PATH=.` in our app to [improve local `require()`](https://gist.github.com/branneman/8048520). AVA (version 0.11.0) has problems with it, though.

**flat-file structure**:
```.js
// foo/index.js
export const foo = 'bar'
```

```.js
// test/foo.js
import test from 'ava'

import { foo } from 'foo'

test('foo should be bar', t => {
  t.same(foo, 'bar')
})
```

```
> NODE_PATH=. ava

  1 failed

  1. foo should be bar

  t.same(foo, 'bar')
         |
         undefined

  AssertionError: undefined === 'bar'
    Test.fn (test/foo.js:6:5)
```

**nested-file structure**
```.js
// foo/bar/index.js
export const foo = 'bar'
```

```.js
// test/foo.js
import test from 'ava'

import { foo } from 'foo/bar'

test('foo should be bar', t => {
  t.same(foo, 'bar')
})
```

```
> NODE_PATH=. ava

Error: Cannot find module 'foo/bar'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/inyono/Projects/flitt/test/foo.js:9:12)
    at Module._compile (module.js:435:26)
    at Object.extensions.(anonymous function) [as .js] (/Users/inyono/Projects/flitt/node_modules/ava/node_modules/require-precompiled/index.js:13:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/inyono/Projects/flitt/node_modules/ava/lib/test-worker.js:85:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

  ✖ test/foo.js exited with a non-zero exit code: 1
```

**Comment by jamestalmage** [comment] 2016-02-06 01:52
[Conclusion #4](https://gist.github.com/branneman/8048520#conclusion) from that article: 

> Setting application-specific settings as environment variables globally or in your current shell is an anti-pattern

That said, not sure why this would not work. The `NODE_PATH` environment variable must be being ignored somehow.

**Comment by inyono** [comment] 2016-02-06 01:59
I'm not super happy with the `NODE_PATH` solution myself, but it fits our use case quite well (especially ES6 modules hinder some other viable solutions). We didn't run into problems with mocha though.

If it's a beginner-friendly issue, I'd be glad to help.

**Comment by jamestalmage** [comment] 2016-02-06 02:55
> If it's a beginner-friendly issue

I honestly don't know if it is. Feel free to give it a go. I would start by checking that neither [this bit](https://github.com/sindresorhus/ava/blob/master/lib/test-worker.js#L86-L90) or [`require-precompiled`](https://github.com/jamestalmage/require-precompiled) are the problem.

**Comment by inyono** [comment] 2016-02-06 19:54
I will give it a shot tomorrow, thanks for the pointers.

**Comment by ingro** [comment] 2016-02-08 14:57
I'm stuck with the same problem, @inyono did you find a workaround or the cause of this issue?

**Comment by ingro** [comment] 2016-02-08 15:46
I think I've got something, as @jamestalmage suggested inside test-worker.js module:
```javascript
module.constructor._nodeModulePaths = function () {
	var ret = oldNodeModulesPaths.apply(this, arguments);
	ret.push(nodeModulesDir);
	return ret;
};
```

Seems like `ret` doesn't contain the additional paths specified with the `NODE_PATH` env variable:

```javascript
[ 'D:\\projects\\app\\node_modules\\babel-core\\node_modules',
  'D:\\projects\\app\\node_modules',
  'D:\\projects\\node_modules',
  'D:\\node_modules',
  'D:\\projects\\app\\node_modules\\ava\\node_modules' ]
```

I tried naively to do this:

```javascript
module.constructor._nodeModulePaths = function () {
	var ret = oldNodeModulesPaths.apply(this, arguments);
	ret.push(nodeModulesDir);
	if (process.env.NODE_PATH) {
		const additionalPath = path.join(process.cwd(), process.env.NODE_PATH);
		ret.push(additionalPath);
	}
	return ret;
};

```

But the problem is that `process.cwd()` points to the directory where the test file is, and not on the root of my application, so that didn't work.

A ugly solution could be to seth `NODE_PATH` as absolute but that would have a lot of downsides. I did not fully understand how the code inside `test-worker.js` gets invoked, if someone can clarify it maybe the solution could be at hand.

**Comment by inyono** [comment] 2016-02-08 17:07
Yeah, I it works with absolute paths. Considering https://gist.github.com/branneman/8048520#6-the-hack, I looked into [_initPaths()](https://github.com/nodejs/node/blob/master/lib/module.js#L473-L478), but `initPaths()` also works with the relative path and does not create an absolute one...

**Comment by inyono** [comment] 2016-02-08 17:10
Seems like `cwd` is set here: https://github.com/sindresorhus/ava/blob/master/lib/fork.js#L20

**Comment by inyono** [comment] 2016-02-08 17:20
See PR. I found a fix that at least works in my minimal example. Because I have failing tests in both my branch and on master, I guess I did something wrong, though ;)

**Comment by ingro** [comment] 2016-02-09 09:15
I tried another approach, hope one of them could be merged :)

**Closed** 2016-02-16 10:50 UTC
